import React, { useState } from 'react';
import '../CSS/SignUp.css';
import { useNavigate } from 'react-router-dom';



const countries = [
    {
        name: 'India',
        states: [
            { name: 'Andhra Pradesh', districts: ['Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Kadapa', 'Krishna', 'Kurnool', 'Nellore', 'Prakasam', 'Srikakulam', 'Visakhapatnam', 'Vizianagaram', 'West Godavari'] },
            { name: 'Arunachal Pradesh', districts: ['Anjaw', 'Changlang', 'Dibang Valley', 'East Kameng', 'East Siang', 'Kamle', 'Kra Daadi', 'Kurung Kumey', 'Lepa Rada', 'Lohit', 'Longding', 'Lower Dibang Valley', 'Lower Siang', 'Lower Subansiri', 'Namsai', 'Pakke Kessang', 'Papum Pare', 'Shi Yomi', 'Siang', 'Tawang', 'Tirap', 'Upper Siang', 'Upper Subansiri', 'West Kameng', 'West Siang'] },
            {
                name: 'Karnataka', districts: ['Bagalkot',
                    'Bangalore',
                    'Belagavi',
                    'Belgaum',
                    'Bellary',
                    'Betigeri',
                    'Bhadravati',
                    'Bidar',
                    'Bijapur',
                    'Chamarajanagara',
                    'Chikkaballapura',
                    'Chikkamagaluru',
                    'Chitradurga',
                    'Dakshina Kannada',
                    'Davanagere',
                    'Dharwad',
                    'Gadag',
                    'Gangawati',
                    'Gulbarga',
                    'Hassan',
                    'Haveri',
                    'Hospet',
                    'Hubli',
                    'Kalaburagi',
                    'Kodagu',
                    'Kolar',
                    'Koppal',
                    'Mandya',
                    'Mangalore',
                    'Mysore',
                    'Raichur',
                    'Ramanagara',
                    'Ranibennur',
                    'Robertson Pet',
                    'Shimoga',
                    'Tumkur',
                    'Udupi',
                    'Uttara Kannada',
                    'Vijayanagar',
                    'Vijayapura',
                    'Yadgir',]
            },
            {
                name: 'Kerala', districts: ['Alappuzha',
                    'Chalakudy',
                    'Changanassery',
                    'Cherthala',
                    'Ernakulam',
                    'Idukki',
                    'Kanhangad',
                    'Kannur',
                    'Kasaragod',
                    'Kayamkulam',
                    'Kochi',
                    'Kollam',
                    'Kothamangalam',
                    'Kottayam',
                    'Kozhikode',
                    'Malappuram',
                    'Ottappalam',
                    'Palakkad',
                    'Pathanamthitta',
                    'Thiruvananthapuram',
                    'Thrissur',
                    'Wayanad',]
            },
            {
                name: 'Goa', districts: ['Bicholim',
                    'Canacona',
                    'Cuncolim',
                    'Curchorem',
                    'Mapusa',
                    'Margao',
                    'Mormugao',
                    'Panaji',
                    'Pernem',
                    'Ponda',
                    'Quepem',
                    'Sanguem',
                    'Sanquelim',
                    'Valpoi',]
            },
            {
                name: 'Uttar Pradesh', districts: ['Agra',
                    'Akbarpur',
                    'Aligarh',
                    'Ambedkar Nagar',
                    'Amroha',
                    'Awagarh',
                    'Ayodhya',
                    'Azamgarh',
                    'Baduan',
                    'Bahraich',
                    'Ballia',
                    'Banda',
                    'Barabanki',
                    'Bareilly',
                    'Basti',
                    'Bijnor',
                    'Budaun',
                    'Bulandshahr',
                    'Chandausi',
                    'Deoria',
                    'Etah', 'Etawah',
                    'Farrukhabad',
                    'Fatehgarh',
                    'Fatehpur',
                    'Firozabad',
                    'Gautam Buddha Nagar',
                    'Ghaziabad',
                    'Ghazipur',
                    'Gonda',
                    'Gorakhpur',
                    'Greater Noida',
                    'Hapur',
                    'Hardoi',
                    'Hathras',
                    'Jalaun',
                    'Jaunpur',
                    'Jhansi',
                    'Kanpur',
                    'Kasganj',
                    'Khurja',
                    'Lakhimpur'

                ]
            },
            {
                name: 'West Bengal', districts: ['Asansol',
                    'Alipurduar',
                    'Ashokenagar Kalyangarh',
                    'Baharampur',
                    'Baidyabati',
                    'Bally',
                    'Bally Town',
                    'Balurghat',
                    'Bankura',
                    'Bansberia',
                    'Baranagar',
                    'Barasat',
                    'Barddhaman',
                    'Barrackpur',
                    'Basirhat',
                    'Bhadreswar',
                    'Bhatpara',
                    'Bidhan Nagar',
                    'Birbhum',
                    'Bongaon',
                    'Champdani',
                    'Chandannagar',
                    'Chinsurah',
                    'Cooch Behar',
                    'Dabgram',
                    'Dakshin Dinajpur',
                    'Darjiling',
                    'Dum Dum',
                    'Durgapur',
                    'English Bazar',
                    'Habra',
                    'Haldia',
                    'Halisahar',
                    'Hooghly',
                    'Howrah',
                    'Hugli ',
                    'Jalpaiguri',
                    'Jamuria',
                    'Jhargram',
                    'Kalimpong',
                    'Kalyani',
                    'Kamarhati',
                    'Kanchrapara',
                    'Kharagpur',
                    'Khardaha',
                    'Kolkata',
                    'Krishnanagar',
                    'Kulti',
                    'Madhyamgram',
                    'Maheshtala',
                    'Maldah',

                    'Medinipur',
                    'Murshidabad',
                    'Nabadwip',
                    'Nadia',
                    'Naihati',
                    'North 24 Parganas',
                    'North Barrackpur',
                    'North Dum Dum',
                    'Panihati',
                    'Paschim Bardhaman',
                    'Paschim Medinipur',
                    'Purba Bardhaman',
                    'Purba Medinipur',
                    'Purulia',
                    'Puruliya',
                    'Raiganj',
                    'Rajarhat Gopalpur',
                    'Rajpur Sonarpur',
                    'Raniganj',
                    'Rishra',
                    'Santipur',
                    'Serampore',
                    'Siliguri',
                    'South 24 Parganas',
                    'South Dum Dum',
                    'Titagarh',
                    'Uluberia',
                    'Uttar Dinajpur',
                    'Uttarpara Kotrung',

                ]
            },
            {
                name: 'Uttarakhand', districts: ['Uttrarakhand',
                    'Almora',
                    'Bageshwar',
                    'Chamoli',
                    'Champawat',
                    'Dehradun',
                    'Haldwani',
                    'Haridwar',
                    'Kashipur',
                    'Nainital',
                    'Pauri Garhwal',
                    'Pithoragarh',
                    'Rishikesh',
                    'Roorkee',
                    'Rudraprayag',
                    'Rudrapur',
                    'Tehri Garhwal',
                    'Udham Singh Nagar',
                    'Uttarkashi',
                    'Kathgodam',

                ]
            },
            {
                name: 'Tripura', districts: ['Agartala',
                    'Amarpur',
                    'Ambassa',
                    'Belonia',
                    'Bishalgarh',
                    'Dhalai',
                    'Dharmanagar',
                    'Gomati',
                    'Jirania',
                    'Kailashahar',
                    'Kamalpur',
                    'Khowai',
                    'Kumarghat',
                    'Melaghar',
                    'Mohanpur',
                    'North Tripura',
                    'Panisagar',
                    'Ranirbazar',
                    'Sabroom',
                    'Santirbazar',
                    'Sipahijala',
                    'Sonamura',
                    'South Tripura',
                    'Teliamura',
                    'Udaipur',
                    'Unakoti',
                    'West Tripura',

                ]
            },
            {
                name: 'Sikkim', districts: ['Gangtok',
                    'Geyzing',
                    'Gyalshing',
                    'Jorethang',
                    'Mangan',
                    'Namchi',
                    'Naya Bazar',
                    'Pakyong',
                    'Rangpo',
                    'Singtam',
                    'Soreng',

                ]
            },
            {
                name: 'Rajasthan', districts: ['Ajmer',
                    'Alwar',
                    'Banswara',
                    'Baran',
                    'Barmer',
                    'Beawar',
                    'Bharatpur',
                    'Bhilwara',
                    'Bhiwadi',
                    'Bikaner',
                    'Bundi',
                    'Chittaurgarh (Chittorgarh)',
                    'Churu',
                    'Dausa',
                    'Dhaulpur (Dholpur)',
                    'Dungarpur',
                    'Ganganagar (Sri Ganganagar)',
                    'Hanumangarh',
                    'Jaipur',
                    'Jaisalmer',
                    'Jalor (Jalore)',
                    'Jhalawar',
                    'Jhunjhunu',
                    'Jodhpur',
                    'Karauli',
                    'Kishangarh',
                    'Kota',
                    'Nagaur',
                    'Pali',
                    'Pratapgarh',
                    'Rajsamand',
                    'Sawai Madhopur',
                    'Sikar',
                    'Sirohi',
                    'Tonk',
                    'Udaipur',

                ]
            },
            {
                name: 'Punjab', districts: ['Abohar',
                    'Amritsar',
                    'Barnala',
                    'Batala',
                    'Bathinda',
                    'Chandigarh',
                    'Faridkot',
                    'Fatehgarh Sahib',
                    'Fazilka',
                    'Firozpur',
                    'Gurdaspur',
                    'Hoshiarpur',
                    'Jalandhar',
                    'Kapurthala',
                    'Khanna',
                    'Ludhiana',
                    'Malerkotla',
                    'Mansa',
                    'Moga',
                    'Mohali',
                    'Muktsar',
                    'Pathankot',
                    'Patiala',
                    'Rupnagar',
                    'Sahibzada Ajit Singh Nagar',
                    'Sangrur',
                    'Shahid Bhagat Singh Nagar',
                    'Sri Muktsar Sahib',
                    'Tarn Taran',

                ]
            },
            {
                name: 'Orissa', districts: ['Anandpur',
                    'Angul',
                    'Balangir',
                    'Balangir District',
                    'Balasore',
                    'Bargarh',
                    'Bargarh District',
                    'Bhadrak',
                    'Bhanjanagar',
                    'Bhubaneswar',
                    'Boudh',
                    'Cuttack',
                    'Debagarh',
                    'Dhenkanal',
                    'Gajapati',
                    'Ganjam',
                    'Ganjam District',
                    'Jagatsinghpur',
                    'Jajpur',
                    'Jharsuguda',
                    'Kalahandi',
                    'Kandhamal',
                    'Kendrapara',
                    'Kendujhar',
                    'Kendujhar District',
                    'Khordha',
                    'Khordha District',
                    'Koraput',
                    'Malkangiri',
                    'Mayurbhanj',
                    'Mayurbhanj District',
                    'Nabarangpur',
                    'Nayagarh',
                    'Nuapada',
                    'Nyayagarh',
                    'Padampur',
                    'Puri',
                    'Rairangpur',
                    'Rayagada',
                    'Rourkela',
                    'Sambalpur',
                    'Subarnapur',
                    'Sundargarh',
                    'Sundargarh district',
                    'Titlagarh',

                ]
            },
            {
                name: 'Nagaland', districts: ['Changtongya',
                    'Chumukedima',
                    'Dimapur',
                    'Diphupar ‘A’',
                    'Jalukie',
                    'Kiphire',
                    'Kohima',
                    'Kohima Village',
                    'Kuda',
                    'Longleng',
                    'Medziphema',
                    'Mokokchung',
                    'Mon Town',
                    'Naginimora',
                    'Peren',
                    'Pfutsero',
                    'Phek',
                    'Puranabazar ‘A’',
                    'Rangapahar',
                    'Satakha Hq.',
                    'Tseminyu',
                    'Tsudikong',
                    'Tuensang',
                    'Tuli',
                    'Wokha',
                    'Zunheboto',

                ]
            },

            {
                name: 'Mizoram', districts: ['Aizawl',
                    'Bairabi',
                    'Biate',
                    'Champhai',
                    'Darlawn',
                    'Hnahthial',
                    'Khawhai',
                    'Khawzawl',
                    'Kolasib',
                    'Lawngtlai',
                    'Lengpui',
                    'Lunglei',
                    'Mamit',
                    'N. Kawnpui',
                    'North Vanlaiphai',
                    'Saiha',
                    'Sairang',
                    'Saitual',
                    'Serchhip',
                    'Thenzawl',
                    'Tlabung',
                    'Vairengte',
                    'Zawlnuam',

                ]
            },
            {
                name: 'Meghalaya', districts: ['Baghmara',
                    'Cherrapunjee(Cherrapunji)',
                    'Jowai',
                    'Lawsohtun',
                    'Madanriting(Madanrting)',
                    'Mairang',
                    'Mawlai',
                    'Mawpat',
                    'Nongkseh',
                    'Nongmynsong',
                    'Nongpoh',
                    'Nongstoin',
                    'Nongthymmai',
                    'Pynthormukhrah(Pynthorumkhrah)',
                    'Resubelpara',
                    'Shillong',
                    'Shillong Cantonment',
                    'Tura',
                    'Umlyngka',
                    'Umpling',
                    'Umroi',
                    'Williamnagar',

                ]
            },
            {
                name: 'Manipur', districts: ['Bishnupur',
                    'Chandel ',
                    'Churachandpur',
                    'Imphal East',
                    'Imphal West',
                    'Jiribam',
                    'Kakching',
                    'Kamjong',
                    'Kangpokpi',
                    'Noney',
                    'Pherzawl',
                    'Senapati',
                    'Tamenglong',
                    'Tengnoupal',
                    'Thoubal',
                    'Ukhrul',

                ]
            },
            {
                name: 'Maharashtra', districts: ['Achalpur',
                    'Ahmednagar',
                    'Akola',
                    'Ambarnath',
                    'Amravati',
                    'Aurangabad',
                    'Badlapur',
                    'Barshi',
                    'Beed',
                    'Bhiwandi-Nizampur',
                    'Bhusawal',
                    'Chandrapur',
                    'Chiplun',
                    'Dhule',
                    'Gondia',
                    'Hinganghat',
                    'Ichalkaranji',
                    'Jalgaon',
                    'Jalna',
                    'Kalyan-Dombivli',
                    'Kamptee',
                    'Karad',
                    'Kolhapur',
                    'Latur',
                    'Malegaon',
                    'Mira-Bhayandar',
                    'Miraj',
                    'Mumbai',
                    'Mumbai City, Mumbai Suburban',
                    'Nagpur',
                    'Nanded',
                    'Nanded-Waghala',
                    'Nandurbar',
                    'Nashik',
                    'Navi Mumbai',
                    'Osmanabad',
                    'Palghar',
                    'Panvel',
                    'Parbhani',
                    'Parli',
                    'Pimpri Chinchwad',
                    'Pune',
                    'Raigad',
                    'Ratnagiri ',
                    'Sangli',
                    'Sangli-Miraj-Kupwad',
                    'Satara',
                    'Solapur',
                    'Thane',
                    'Udgir',
                    'Ulhasnagar',
                    'Vasai-Virar',
                    'Wardha',
                    'Yavatmal',

                ]
            },
            {
                name: 'Madhya Pradesh', districts: ['Betul',
                    'Betul district',
                    'Bhind',
                    'Bhind district',
                    'Bhopal',
                    'Bhopal district',
                    'Burhanpur',
                    'Burhanpur district',
                    'Chambal',
                    'Chambal district',
                    'Chhatarpur',
                    'Chhatarpur district',
                    'Chhindwara',
                    'Chhindwara district',
                    'Damoh',
                    'Damoh district',
                    'Datia',
                    'Datia district',
                    'Dewas',
                    'Dewas district',
                    'Dhar district',
                    'Dindori',
                    'Dindori district',
                    'Gadarwara',
                    'Guna',
                    'Guna district',
                    'Gwalior',
                    'Gwalior district',
                    'Indore',
                    'Indore district',
                    'Itarsi',
                    'Jabalpur',
                    'Jabalpur district',
                    'Katni',
                    'Katni district',
                    'Khandwa',
                    'Khandwa district',
                    'Khargone',
                    'Khargone district',
                    'Mandsaur',
                    'Mandsaur district',
                    'Nagda',
                    'Narmadapuram',
                    'Narmadapuram district',
                    'Narsinghpur district',
                    'Neemuch',
                    'Neemuch district',
                    'Pithampur',
                    'Ratlam',
                    'Ratlam district',
                    'Rewa',
                    'Rewa District',
                    'Sagar',
                    'Sagar district',
                    'Satna',
                    'Satna district',
                    'Sehore',
                    'Sehore district',
                    'Seoni',
                    'Seoni district',
                    'Shivpuri',
                    'Shivpuri district',
                    'Singrauli',
                    'Singrauli district',
                    'Ujjain',
                    'Ujjain district',
                    'Vidisha',
                    'Vidisha district',

                ]
            },
            {
                name: 'Jharkhand', districts: ['Adityapur',
                    'Bokaro',
                    'Bokaro district',
                    'Bokaro Steel City',
                    'Chirkunda',
                    'Deoghar',
                    'Deoghar district',
                    'Dhanbad',
                    'Dhanbad district',
                    'East Singhbhum',
                    'Giridih',
                    'Giridih district',
                    'Hazaribagh',
                    'Hazaribagh district',
                    'Jamshedpur',
                    'Mango',
                    'Medininagar',
                    'Medininagar (Daltonganj)',
                    'Palamu',
                    'Palamu district',
                    'Phusro–Bermo–Bokaro Thermal',
                    'Ramgarh',
                    'Ramgarh district',
                    'Ranchi',
                    'Ranchi district',
                    'Seraikela Kharsawan',

                ]
            },
            {
                name: 'Himachal Pradesh', districts: ['Bilaspur',
                    'Chamba',
                    'Dharamshala',
                    'Hamirpur',
                    ' Kullu',
                    'Mandi',
                    'Palampur',
                    'Shimla',
                    'Solan',
                    'Una',
                    'Kangra',
                    'Lahaul',
                    'Simraur',
                    'Spiti',
                    'Kinnaur',

                ]
            },
            {
                name: 'Haryana', districts: ['Ambala',
                    'Bhiwani',
                    'Charkhi Dadri',
                    'Faridabad',
                    'Fatehabad',
                    'Gurugram',
                    'Hisar',
                    'Jhajjar',
                    'Jind',
                    'Kaithal',
                    'Karnal',
                    'Kurukshetra',
                    'Mahendragarh',
                    'Narnaul',
                    'Nuh',
                    'Palwal',
                    'Panchkula',
                    'Panipat',
                    'Rewari',
                    'Rohtak',
                    'Sirsa',
                    'Sonipat',
                    'Yamunanagar',
                    'Bahadurgarh',
                    'Kosi',
                    'Pundri',
                    'Thanesar',

                ]
            },
            {
                name: 'Gujarat', districts: ['Ahmedabad',
                    'Amreli',
                    'Anand',
                    'Banaskantha',
                    'Bharuch',
                    'Bhavnagar',
                    'Bhuj',
                    'Botad',
                    'Dahod',
                    'Deesa',
                    'Gandhidham',
                    'Gandhinagar',
                    'Gir Somnath',
                    'Godhra',
                    'Gondal',
                    'Jamnagar',
                    'Jetpur',
                    'Junagadh',
                    'Kalol',
                    'Kheda',
                    'Kutch',
                    'Mehsana',
                    'Morbi',
                    'Nadiad',
                    'Navsari',
                    'Palanpur',
                    'Panchmahal',
                    'Patan',
                    'Porbandar',
                    'Rajkot',
                    'Surat',
                    'Surendranagar',
                    'Vadodara',
                    'Valsad',
                    'Vapi',
                    'Veraval',

                ]
            },
            {
                name: 'Chhattisgarh', districts: ['Ahiwara',
                    'Akaltara',
                    'Ambagarh Chowki',
                    'Ambikapur',
                    'Ambikapur',
                    'Arang',
                    'Bade Bacheli',
                    'Baghbahara',
                    'Baikunthpur',
                    'Baloda',
                    'Baloda bazar',
                    'Balodabazar Bhatapara',
                    'Balrampur',
                    'Bastar district',
                    'Bemetra',
                    'Bhatgaon',
                    'Bhilai',
                    'Bhilai-Durg',
                    'Bijapur',
                    'Bilaspur',
                    'Bilaspur district',
                    'Bilha',
                    'Bishrampur',
                    'Bodri',
                    'Chandrapur',
                    'Chhuikhadan',
                    'Chirmiri',
                    'Dabhra',
                    'Dalli Rajhara',
                    'Dantewada',
                    'Dhamdha',
                    'Dhamtari',
                    'Dhamtari district',
                    'Dharamjaigarh',
                    'Dongergaon',
                    'Durg',
                    'Durg district',
                    'Gandai',
                    'Gaurella',
                    'Gaurella-Pendra-Marwahi',
                    'Gharghoda',
                    'Jagdalpur',
                    'Janjgir–Champa',
                    'Jashpur',
                    'Jashpur Nagar',
                    'Kabirdham',
                    'Kanker',
                    'Katghora',
                    'Khairagarh',
                    'Khamharia',
                    'Kharod',
                    'Kharsia',
                    'Kirandul',
                    'Kondagaon',
                    'Korba',
                    'Korba district',
                    'Koriya',
                    'Kota',
                    'Kurud',
                    'Lormi',
                    'Mahasamund',
                    'Mahasamund district',
                    'Manendragarh',
                    'Manendragarh-Chirmiri-Bharatpur district',
                    'Mungeli',
                    'Narayanpur',
                    'Naya Baradwar',
                    'Odagi',
                    'Pandariya',
                    'Patan',
                    'Pathalgaon',
                    'Pendra',
                    'Pithora',
                    'Pratappur',
                    'Raigarh',
                    'Raigarh district',
                    'Raipur',
                    'Raipur district',
                    'Rajnandgaon',
                    'Rajnandgaon district',
                    'Ramanujganj',
                    'Ratanpur',
                    'Sakti',
                    'Saraipali',
                    'Sarangarh',
                    'Shivrinarayan',
                    'Simga',
                    'Sukma',
                    'Surajpur',
                    'Surajpur district',
                    'Surguja district',
                    'Takhatpur',
                    'Telgaon',

                ]
            },
            {
                name: 'Bihar', districts: ['Arrah',
                    'Begusarai',
                    'Bettiah',
                    'Bhagalpur',
                    'Bhagalpur district',
                    'Bihar Sharif',
                    'Buxar',
                    'Buxar district',
                    'Chhapra',
                    'Danapur',
                    'Darbhanga',
                    'Darbhanga district',
                    'East Champaran',
                    'Gaya',
                    'Gaya district',
                    'Katihar',
                    'Katihar district',
                    'Madhubani',
                    'Mehsi',
                    'Motihari',
                    'Munger',
                    'Muzaffarpur',
                    'Muzaffarpur district',
                    'Patna',
                    'Patna district',
                    'Purnia',
                    'Purnia district',
                    'Saharsa',
                    'Samastipur',
                    'Saran district',
                    'Sasaram',
                    'Sitamarhi',
                    'West Champaran district',

                ]
            },
            {
                name: 'Assam', districts: ['Bongaigaon',
                    'Chirang',
                    'Cachar',
                    'Dibrugarh',
                    'Guwahati',
                    'Jorhat',
                    'Kamrup Metropolitan',
                    'Silchar',
                    'Sonitpur',
                    'Tezpur',
                    'Tinsukia',

                ]
            },
            {
                name: 'Andaman & Nicobar', districts: ['Bakultala',
                    'Bambooflat',
                    'Garacharma',
                    'Malacca',
                    'Mayabunder',
                    'Nicobar',
                    'North and Middle Andaman',
                    'Port Blair',
                    'Prothrapur',
                    'South Andaman',

                ]
            },
            { name: 'Dadra and Nagar Haveli', districts: ['Daman', 'Diu',] },
            {
                name: 'Lakshadweep', districts: ['Agatti Island',
                    'Amini',
                    'Andrott',
                    'Bangaram Atoll',
                    'Bitra',
                    'Chetlat Island',
                    'Kadmat Island',
                    'Kalpeni',
                    'Kavaratti',
                    'Kiltan',
                    'Minicoy',

                ]
            },
            {
                name: 'Delhi', districts: ['Aali',
                    'Ali Pur',
                    'Asola',
                    'Aya Nagar',
                    'Babar Pur',
                    'Bakhtawar Pur',
                    'Bakkar Wala',
                    'Bankauli',
                    'Bankner',
                    'Bapraula',
                    'Baqiabad',
                    'Barwala',
                    'Bawana',
                    'Begum Pur',
                    'Bhalswa Jahangir Pur',
                    'Bhati',
                    'Bhor Garh',
                    'Burari',
                    'Chandan Hola',
                    'Chattar Pur',
                    'Chhawala (Chhawla)',
                    'Chilla Saroda Bangar',
                    'Chilla Saroda Khadar',
                    'Dallo Pura',
                    'Darya Pur Kalan',
                    'Dayal Pur',
                    'Deoli',
                    'Dera Mandi',
                    'Dindar Pur',
                    'Fateh Pur Beri',
                    'Gharoli',
                    'Gharonda Neemka Bangar (Patparganj)',
                    'Gheora',
                    'Ghitorni',
                    'Gokal Pur',
                    'Hastsal',
                    'Ibrahim Pur',
                    'Jaffar Pur Kalan',
                    'Jaffrabad',
                    'Jait Pur',
                    'Jharoda Kalan',
                    'Jharoda Majra Burari',
                    'Jiwan Pur (Johri Pur)',
                    'Jona Pur',
                    'Kair',
                    'Kamal Pur Majra Burari',
                    'Kanjhawala',
                    'Kapas Hera',
                    'Karala',
                    'Karawal Nagar',
                    'Khajoori Khas',
                    'Khan Pur Dhani',
                    'Khera',
                    'Khera Kalan',
                    'Khera Khurd',
                    'Kirari Suleman Nagar',
                    'Kondli',
                    'Kotla Mahigiran',
                    'Kusum Pur',
                    'Lad Pur',
                    'Libas Pur',
                    'Maidan Garhi',
                    'Malik Pur Kohi (Rang Puri)',
                    'Mandoli',
                    'Mir Pur Turk',
                    'Mithe Pur',
                    'Mitraon',
                    'Mohammad Pur Majri',
                    'Molar Band',
                    'Moradabad Pahari',
                    'Mubarak Pur Dabas',
                    'Mukand Pur',
                    'Mukhmel Pur',
                    'Mundka',
                    'Mustafabad',
                    'Nangli Sakrawati',
                    'Nangloi Jat',
                    'Neb Sarai',
                    'New Delhi',
                    'Nilothi',
                    'Nithari',
                    'Pehlad Pur Bangar',
                    'Pooth Kalan',
                    'Pooth Khurd',
                    'Pul Pehlad',
                    'Qadi Pur',
                    'Quammruddin Nagar',
                    'Qutab Garh',
                    'Raja Pur Khurd',
                    'Rajokri',
                    'Raj Pur Khurd',
                    'Rani Khera',
                    'Roshan Pura (Dichaon Khurd)',
                    'Sadat Pur Gujran',
                    'Sahibabad Daulat Pur',
                    'Saidabad',
                    'Saidul Azaib',
                    'Sambhalka',
                    'Shafi Pur Ranhola',
                    'Shakar Pur Baramad',
                    'Siras Pur',
                    'Sultan Pur',
                    'Sultan Pur Majra',
                    'Taj Pul',
                    'Tigri',
                    'Tikri Kalan',
                    'Tikri Khurd',
                    'Tilang Pur Kotla',
                    'Tukhmir Pur',
                    'Ujwa',
                    'Ziauddin Pur',

                ]
            },
            {
                name: 'Chandigarh', districts: ['Atawa',
                    'Atawa Choa',
                    'Badheri',
                    'Bahlana',
                    'Bahlolpur',
                    'Bajwara',
                    'Bijwari Bakhta',
                    'Burail',
                    'Buterla',
                    'Dadu Majra',
                    'Dariya',
                    'Dhanas',
                    'Dhanauran',
                    'Fatehgarh',
                    'Gurudwara',
                    'Hala Majra',
                    'Jhampur',
                    'Kaimbwala',
                    'Kanji Maira',
                    'Kansil',
                    'Kanthara',
                    'Khoda Jassu',
                    'Kujheri',
                    'Kursan',
                    'Madanpur',
                    'Mahla Majra',
                    'Malak',
                    'Mariwala Town',
                    'Mastgarh',
                    'Moloia',
                    'Palsaura',
                    'Purnapani',
                    'Raipur',
                    'Raj Bhavan Haryana',
                    'Raj Bhavan Punjab',
                    'Sadoriaja Goth',
                    'Saini Majra',
                    'Sangariwala',
                    'Sarangpur',
                    'Shahpur Cholian',
                    'Shahzadpur',
                    'Togan',

                ]
            },
            {
                name: 'Ladakh', districts: ['Kargil',
                    'Kargil district',
                    'Karzok',
                    'Khaltse',
                    'Leh',
                    'Leh district',
                    'Nubra',
                    'Nubra Valley',
                    'Padum',
                    'Sanku',
                    'Thukje',

                ]
            },
            {
                name: 'J&K', districts: ['Samba',
                    'Samba district',
                    'Shopian',
                    'Shopian district',
                    'Srinagar',
                    'Srinagar district',
                    'Udhampur',
                    'Udhampur district',

                ]
            },

        ],
    },
    {
        name: 'NEPAL', states: [
            {
                name: 'Bagmati', districts: ['Bhaktapur',
                    'Bhaktapur District',
                    'Bharatpur',
                    'Bhimeshwar',
                    'Bidur',
                    'Chautara',
                    'Chitwan District',
                    'Dhading District',
                    'Dhulikhel',
                    'Dhunche',
                    'Dolakha District',
                    'Hetauda',
                    'Kamalamai',
                    'Kathmandu',
                    'Kathmandu District',
                    'Kavrepalanchok District',
                    'Lalitpur',
                    'Lalitpur District',
                    'Makwanpur District',
                    'Manthali',
                    'Nilkantha',
                    'Nuwakot District',
                    'Ramechhap District',
                    'Rasuwa District',
                    'Sindhuli District',
                    'Sindhupalchok District',

                ]
            },

            {
                name: 'Koshi', districts: ['Aamchok',
                    'Aathrai',
                    'Aathrai Triveni',
                    'Aiselukharka',
                    'Arjundhara',
                    'Arun',
                    'Baraha',
                    'Barahpokhari',
                    'Barhadashi',
                    'Barju',
                    'Belaka',
                    'Belbari',
                    'Bhadrapur',
                    'Bhojpur',
                    'Bhokraha',
                    'Bhot Khola',
                    'Biratnagar',
                    'Birtamod',
                    'Buddha Shanti',
                    'Budi Ganga',
                    'Chainpur',
                    'Champadevi',
                    'Chaubise',
                    'Chaudandigadhi',
                    'Chhathar',
                    'Chhathar Jorpati',
                    'Chichila',
                    'Chisankhugadhi',
                    'Chulachuli',
                    'Damak',
                    'Deumai',
                    'Dewangunj',
                    'Dhankuta',
                    'Dhanpalthan',
                    'Dharan',
                    'Dharmadevi',
                    'Diprung',
                    'Dudhkoshi',
                    'Duhabi',
                    'Gadhi',
                    'Gauradaha',
                    'Gaurigunj',
                    'Gramthan',
                    'Haldibari',
                    'Halesi Tuwachung',
                    'Harinagara',
                    'Hatuwagadhi',
                    'Hilihang',
                    'Ilam',
                    'Inaruwa',
                    'Itahari',
                    'Jahada',
                    'Jantedhunga',
                    'Jhapa',
                    'Kachankawal',
                    'Kamal',
                    'Kanepokhari',
                    'Kankai',
                    'Katahari',
                    'Katari',
                    'Kepilasgadhi',
                    'Kerabari',
                    'Khalsa Chhintang Sahidbhumi',
                    'Khandbari',
                    'Khiji Demba',
                    'Khotang',
                    'Khumbu Pasang Lhamu',
                    'Koshi',
                    'Kummayak',
                    'Laligurans',
                    'Letang',
                    'Likhu',
                    'Likhu Pike',
                    'Limchungbung',
                    'Madi',
                    'Maha Kulung',
                    'Mahalaxmi Municipality',
                    'Mai Jogmai',
                    'Mai Municipality',
                    'Maiwa Khola',
                    'Makalu',
                    'Manebhanjyang',
                    'Mangsebung',
                    'Mechinagar',
                    'Menchayayem',
                    'Meringden',
                    'Miklajung',
                    'Mikwa Khola',
                    'Molung',
                    'Morang District',
                    'Myanglung',
                    'Necha Salyan',
                    'Okhaldhunga',
                    'Pakhribas',
                    'Panchkhapan',
                    'Panchthar',
                    'Pathari Shanischare',
                    'Pathibhara Yangwarak',
                    'Pauwadungma',
                    'Phakphokthum',
                    'Phaktanglung',
                    'Phalelung',
                    'Phalgunanda',
                    'Phedap',
                    'Phidim',
                    'Phungling',
                    'Ramdhuni',
                    'Ramprasad Rai',
                    'Rangeli',
                    'Ratuwamai',
                    'Rautamai',
                    'Rawabesi',
                    'Rong',
                    'Rupakot Majhuwagadhi',
                    'Sabhapokhari',
                    'Sakela',
                    'Salpasilichho',
                    'Sandakpur',
                    'Sangurigadhi',
                    'Sankhuwasabha',
                    'Shadanand',
                    'Shivasatakshi Municipality',
                    'Siddhicharan',
                    'Sidingwa',
                    'Silichong',
                    'Sirijangha',
                    'Solu Dudhkunda',
                    'Solukhumbu',
                    'Sotang',
                    'Sunawarshi',
                    'Sundar Haraicha',
                    'Sunkoshi',
                    'Sunsari',
                    'Sunsari District',
                    'Suryodaya',
                    'Taplejung',
                    'Tapli',
                    'Tehrathum',
                    'Triyuga',
                    'Tumbewa',
                    'Tyamke Maiyunm',
                    'Udayapur',
                    'Udayapurgadhi',
                    'Urlabari',
                    'Yangwarak',

                ]
            },

            {
                name: 'Gandaki', districts: ['Baglung',
                    'Beni',
                    'Besishahar',
                    'Bhanu',
                    'Bhimad',
                    'Devchuli',
                    'Gaindakot',
                    'Galkot',
                    'Galyang',
                    'Gorkha',
                    'Jaimini',
                    'Kaski',
                    'Kawasoti',
                    'Kushma',
                    'Lamgunj',
                    'Madhyabindu',
                    'Myagdi',
                    'Nawalpur',
                    'Palungtar',
                    'Parbat',
                    'Pokhara',
                    'Putalibazar',
                    'Shuklagandaki',
                    'Syangja',
                    'Tanahun',
                    'Vyas',
                    'Waling',
                ]
            },
            {
                name: 'Karnali', districts: ['Birendranagar',
                    'Chandannath',
                    'Dailekh District',
                    'Dolpa District',
                    'Dunai',
                    'Gamgadhi',
                    'Humla District',
                    'Jajarkot District',
                    'Jumla District',
                    'Kalikot District',
                    'Khalanga',
                    'Manma',
                    'Mugu District',
                    'Musikot',
                    'Narayan',
                    'Salyan',
                    'Salyan District',
                    'Simikot',
                    'Surkhet District',
                    'Western Rukum District',

                ]
            },
            {
                name: 'Sudur Pashchim', districts: ['Achham District',
                    'Baitadi District',
                    'Bajhang District',
                    'Bajura District',
                    'Dadeldhura District',
                    'Darchula District',
                    'Doti District',
                    'Kailali District',
                    'Kanchanpur District',

                ]
            },
            {
                name: 'Lumbini', districts: ['Butwal',
                    'Gulariya',
                    'Nepalgunj',
                    'Siddharthanagar',
                    'Sitganga',
                    'Tansen',
                    'Tulsipur',
                ]
            },
            {
                name: 'Madhesh', districts: ['Bara District',
                    'Birgunj',
                    'Dhanusha District',
                    'Gaur',
                    'Jaleshwar',
                    'Janakpur',
                    'Kalaiya',
                ]
            },
            {
                name: 'Madhesh', districts: ['Bara District',
                    'Birgunj',
                    'Dhanusha District',
                    'Gaur',
                    'Jaleshwar',
                    'Janakpur',
                    'Kalaiya',
                ]
            },

        ]
    },
    {
        name: 'SRI LANKA', states: [{
            name: 'Ampara', districts: ['Addalaichchenai',
                'Akkaraipattu',
                'Alayadivembu',
                'Ampara (Namal Oya)',
                'Damana',
                'Dehiattakandiya',
                'Irakkamam (Eragama)',
                'Kalmunai (Muslim)',
                'Kalmunai (Tamil)',
                'Karaitivu',
                'Lahugala',
                'Maha Oya',
                'Navithanveli',
                'Nintavur',
                'Padiyathalawa',
                'Pottuvil',
                'Sainthamaruthu',
                'Sammanthurai',
                'Thirukkovil',
                'Uhana',

            ]
        },
        {
            name: 'Anuradhapura', districts: ['Bulnewa',
                'Eppawala',
                'Galenbindunuwewa',
                'Galnewa',
                'Ganewalpola',
                'Habarana',
                'Horowupotana',
                'Kahatagasdigiliya',
                'Kebitigollawa',
                'Kekirawa',
                'Konapathirawa',
                'Konwewa',
                'Madatugama',
                'Mahailuppallama',
                'Maradankadawala',
                'Medawachchiya',
                'Mihintale',
                'Nachchaduwa',
                'Nochchiyagama',
                'Padawiya',
                'Palugaswewa',
                'Rambewa',
                'Seeppukulama',
                'Talawa',
                'Tambuttegama',
                'Thirappane',
                'Yakalla',
            ]
        },
        {
            name: 'Batticaloa', districts: ['Chenkalady',
                'Eravur',
                'Kalkudah',
                'Kaluvanchikudy',
                'Kathiraveli',
                'Kattankudy',
                'Kiran',
                'Kudumbimalai',
                'Oddamavadi',
                'Pasikudah',
                'Vakarai',
                'Valaichchenai',
                'Vavunathivu',
                'Vellavely'
            ]
        },
        {
            name: 'Colombo', districts: ['Avissawella',
                'Colombo',
                'Dehiwala',
                'Homagama',
                'Kaduwela',
                'Kesbewa',
                'Kolonnawa',
                'Maharagama',
                'Moratuwa',
                'Mount Lavinia',
                'Padukka',
                'Ratmalana',
                'Seethawaka',
                'Sri Jayawardenepura Kotte',
                'Thimbirigasyaya',
            ]
        },
        {
            name: 'Jaffna', districts: ['Achchuveli',
                'Alaveddy',
                'Aliyawalai',
                'Araly',
                'Chankanai',
                'Chavakachcheri',
                'Chunnakam',
                'Erlalai',
                'Kadduvan',
                'Kaithady',
                'Kankesanthurai',
                'Karainagar',
                'Karaveddy',
                'Kayts',
                'Keerimalai',
                'Kerudavil',
                'Kodikamam',
                'Kokkuvil',
                'Kondavil',
                'Kopay',
                'Mallakam',
                'Manipay',
                'Mirusuvil',
                'Moolai',
                'Myliddy',
                'Nagar Kovil',
                'Nallur',
                'Navaly',
                'Navatkuli',
                'Nelliady',
                'Nelliyady',
                'Palaly',
                'Point Pedro',
                'Polikandy',
                'Puttur',
                'Sandilipay',
                'Tellippalai',
                'Thampalai',
                'Thirunelveli',
                'Thondaimanaru',
                'Thoppu',
                'Thumpalai',
                'Tirunelveli East',
                'Tirunelveli West',
                'Udupiddy',
                'Uduthurai',
                'Uduvil',
                'Urelu',
                'Urumpirai',
                'Vaddukkoddai East',
                'Vaddukkoddai West',
                'Vaddukoddai',
                'Valalai',
                'Vallipuram',
                'Valveddi',
                'Varani',
                'Velanai',
                'Vellampakkaddy',
                'Vidattalpalai',
                'Viyaparimulai',

            ]
        },
        {
            name: 'Kilinochchi', districts: ['Kandavalai',
                'Karachchi',
                'Kilinochchi',
                'Pachchilaipalli',
                'Pallai',
                'Poonakary',

            ]
        },
        {
            name: 'Mannar', districts: ['Madhu',
                'Mannar',
                'Manthai West',
                'Musali',
                'Nanaddan',
                'Adampan',
                'Chilawathurai',
            ]
        },
        {
            name: 'Matale', districts: ['Elkaduwa',
                'Galewela',
                'Gammaduwa',
                'Kaikawala',
                'Kawatayamuna',
                'Maligatenna',
                'Nalanda',
                'Naula',
                'Palapathwela',
                'Pallepola',
                'Rattota',
                'Sigiriya',
                'Ukuwela',
                'Wahacotte',
                'Wehera',
                'Yatawatta',

            ]
        },
        {
            name: 'Matara', districts: ['Mirissa',
                'Morawaka',
                'Mulatiyana',
                'Nupe',
                'Pasgoda',
                'Pitabeddara',
                'Thelijjawila',
                'Thihagoda',
                'Tihagoda',
                'Weligama',
                'Welihinda',
                'Welipitiya',
                'Mirissa',
                'Morawaka',
                'Mulatiyana',
                'Nupe',
            ]
        },
        {
            name: 'Mullaitivu', districts: ['Ehatugaswewa',
                'Manthai East',
                'Maritimepattu',
                'Mullaitivu',
                'Oddusuddan',
                'Pandiyankulam',
                'Puthukkudiyiruppu',
                'Thunukkai',
                'Weli Oya (Manal Aru)',

            ]
        },
        {
            name: 'Polonnaruwa', districts: ['Bakamuna',
                'Dimbulagala',
                'Elahera',
                'Hingurakgoda',
                'Lankapura',
                'Manampitiya',
                'Medirigiriya',
                'Polonnaruwa',
                'Thalpotha',
            ]
        },
        {
            name: 'Sabaragamuwa', districts: ['Aguruwalla',
                'Ambepussa',
                'Aranayaka',
                'Balangoda',
                'Belihuloya',
                'Bulathkohupitiya',
                'Dehiowita',
                'Deraniyagala',
                'Eheliyagoda',
                'Embilipitiya',
                'Godakawela',
                'Imbulpe',
                'Kalawana',
                'Karawanalla',
                'Kegalle',
                'Kitulgala',
                'Kuruwita',
                'Mawanella',
                'Panamure',
                'Rakwana',
                'Rambukkana',
                'Ratnapura',
                'Ruwanwella',
                'Yatiyanthota',
            ]
        },
        {
            name: 'Sri Jayawardenepura Kotte', districts: ['Bandaranayakapura',
                'Ethul Kotte',
                'Ethul Kotte West',
                'Gangodavila East',
                'Gangodavila North',
                'Gangodavila South',
                'Gangodavila West',
                'Koswatta',
                'Meda Welikada',
                'Moragasmulla',
                'Nawala East',
                'Nawala West',
                'Nugegoda',
                'Nugegoda East',
                'Nugegoda West',
                'Obesekarapura',
                'Pagoda',
                'Pagoda East',
                'Pagoda North',
                'Pagoda South',
                'Pitakotte',
                'Pitakotte East',
                'Pitakotte West',
                'Rajagiriya',
                'Welikada East',
                'Welikada North',
                'Welikada West',
            ]
        },
        {
            name: 'Trincomalee', districts: ['Kantale',
                'Kinniya',
                'Kuchchaveli',
                'Mutur',
                'Nilaveli',
                'Sampur, Trincomalee',
                'Thampalakamam',
                'Uppuveli',

            ]
        },
        {
            name: 'Uva', districts: ['Badulla',
                'Bandarawela',
                'Ella',
                'Haputale',
                'Monaragala',
                'Welimada',
                'Wellawaya',
            ]
        },
        {
            name: 'Vavuniya', districts: ['Cheddikulam',
                'Kurumankadu',
                'Nedunkeni',
                'Omanthai',
                'Pandarikulam',
                'Puliyankulam',

            ]
        },
        {
            name: 'Dehiwela-Mount Lavinia', districts: ['Attidiya',
                'Dehiwala',
                'Kalubowila',
                'Kohuwala',
                'Mount-Lavinia',
                'Nedimala',
                'Ratmalana',


            ]
        },
        {
            name: 'Gampaha', districts: ['Dompe',
                'Gampaha',
                'Ja-Ela',
                'Katana',
                'Kelaniya',
                'Kiridiwela',
                'Mahara',
                'Minuwangoda',
                'Mirigama',
                'Negombo',
                'Nittambuwa',
                'Wattala',

            ]
        },
        {
            name: 'Kalutara', districts: ['Agalawatta',
                'Baduraliya',
                'Bandaragama',
                'Beruwala',
                'Bulathsinhala',
                'Dodangoda',
                'Horana',
                'Ingiriya',
                'Kalutara',
                'Madurawela',
                'Matugama',
                'Millaniya',
                'Palindanuwara',
                'Panadura',
                'Walallavita',


            ]
        },
        {
            name: 'Kurunegala', districts: ['Alawwa',
                'Bingirya',
                'Dambadeniya',
                'Dandagamuwa',
                'Galgamuwa',
                'Girathalana',
                'Giriulla',
                'Gomugomuwa',
                'Hettipola',
                'Hiripitiya',
                'Ibbagamuwa',
                'Maho',
                'Mawathagama',
                'Melsiripura',
                'Narammala',
                'Nikaweratiya',
                'Panagamuwa',
                'Panduwasnuwara',
                'Pannala',
                'Pannawa',
                'Polgahawela',
                'Potuhera',
                'Ridigama',
                'Wariyapola',
                'Yapahuwa',

            ]
        },
        {
            name: 'Mahiyanganaya', districts: ['Ampara',
                'Badulla',
                'Kandy',
                'Monaragala',
                'Polonnaruwa',

            ]
        },
        {
            name: 'Negombo', districts: ['Akkarapanaha',
                'Athgala',
                'Basiyawatte',
                'Bolawalana',
                'Dalupotha',
                'Daluwakotuwa',
                'Dungalpitiya',
                'Duwa',
                'Duwane',
                'Ethukala',
                'Kadirana',
                'Kadolkale',
                'Kamachchodai',
                'Kandawala',
                'Kapumgoda',
                'Katana',
                'Kattuwa',
                'Katunayake',
                'Katuwapitiya',
                'Kimbulapitiya',
                'Kochchikade',
                'Kudapadu',
                'Kurana',
                'Mahahunupitiya',
                'Munnakkarai',
                'Muruthena',
                'Nugawala',
                'Palangathura',
                'Pallansena',
                'Periyamulla',
                'Pitipana',
                'Poruthota',
                'Raheemanabad',
                'Sarakkuwa',
                'Sellakanda',
                'Thaladuwa',
                'Thalahena',
                'Thillanduwa',
                'Thimbirigaskatuwa',
                'Udyar Thoppu',
                'Welihena',
                'Wella veediya',

            ]
        },
        {
            name: 'Nuwara Eliya', districts: ['Agrapatana',
                'Ambewela',
                'Bogawantalawa',
                'Bopattalawa',
                'Dayagama Bazaar',
                'Ginigathena',
                'Haggala',
                'Hanguranketha',
                'Hapugastalawa',
                'Hatton-Dikoya UC',
                'Kandapola',
                'Kotagala',
                'Koththallena',
                'Kotmale',
                'Labukele',
                'Laxapana',
                'Lindula-Talawakele UC',
                'Maskeliya',
                'Nanu Oya',
                'Nildandahinna',
                'Norton',
                'Norton Bridge',
                'Nuwara Eliya',
                'Padiyapelella',
                'Pattipola',
                'Pundaluoya',
                'Ragala',
                'Ramboda',
                'Rikillagaskada',
                'Rozella',
                'Udapussallawa',
                'Walapane',
                'Watawala',

            ]
        },
        {
            name: 'Puttalam', districts: ['Anamaduwa',
                'Battuluoya',
                'Dankotuwa',
                'Eluvankulam',
                'Kalpitiya',
                'Katuneriya',
                'Madampe',
                'Mahawewa',
                'Marawila',
                'Mundel',
                'Nainamadama',
                'Nattandiya',
                'Nuraicholai',
                'Palavi',
                'Thillayadi',
                'Wennappuwa',
            ]
        }, {
            name: 'Sri Jayewardenepura Kotte', districts: ['Bandaranayakapura',
                'Ethulkotte',
                'Gangodavila East',
                'Gangodavila West',
                'Koswatta',
                'Meda Welikada',
                'Moragasmulla',
                'Nawala East',
                'Nawala West',
                'Nugegoda East',
                'Nugegoda West',
                'Obesekarapura',
                'Pagoda North',
                'Pagoda South',
                'Pitakotte',
                'Pitakotte East',
                'Pitakotte West',
                'Rajagiriya',
            ]
        },
        ],
    },
];
function SignUp() {
    const [name, setName] = useState('');
    const [dob, setDob] = useState(null);
    const [selectedGender, setSelectedGender] = useState(null);
    const [selectedCountry, setSelectedCountry] = useState('');
    const [selectedState, setSelectedState] = useState('');
    const [selectedDistrict, setSelectedDistrict] = useState('');
    const [showDatePicker, setShowDatePicker] = useState(false);

    const navigate = useNavigate()



    const handlepressNav = () => {

        // Navigate to the '/SignUp' route
        navigate('/Signup2')

    };


    const onDateChange = (event) => {
        const selectedDate = event.target.value;
        if (selectedDate) {
            setDob(new Date(selectedDate));
        }
    };


    const styles = {

        container: {
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            height: '100vh',
            backgroundColor: '#f5f5f5',
        },
        formContainer: {
            width: '600px', /* Adjust the width as needed */
            height: '800px', /* Adjust the height as needed */
            padding: '20px',
            backgroundColor: 'white',
            borderRadius: '10px',
            boxShadow: '0 0 10px rgba(0, 0, 0, 0.1)',
            alignItems: 'center',
            display: 'flex',
            flexDirection: 'column',
        },
        headerImage: {
            width: '30%',
            alignItems: 'center',
            marginLeft: '10%',
            marginTop: '-5%',
        },
        header2Image: {
            width: '50%',
            marginTop: '2%',
            marginBottom: '5%',
        },
        changeinputContainer: {
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            width: '60%',
            height: '10%',
            borderRadius: '5px',
            overflow: 'hidden',

        },
        changedate: {
            // Default styles for the div
            marginLeft: '-40%',
            // marginTop: '20px', 
            
        },
       
        input: {
            width: '100%',
            height: '75%',
            padding: '10px',
            border: '1px solid #ccc',
            borderRadius: '5px',
            fontSize: '16px',
            boxSizing: 'border-box',
            marginBottom: '10px',
        },
        signUpButton: {
            width: '20%',
            padding: '10px',
            backgroundColor: 'black',
            color: 'white',
            border: 'none',
            borderRadius: '5px',
            fontSize: '16px',
            cursor: 'pointer',
            transition: 'background-color 0.3s',
            marginBottom: '5%',
            marginTop: '10%',
        },
        signupcontiner: {
            marginTop: '5%',
        },
        signup: {
            color: 'red',
        },
    };

    return (
        <div style={styles.container}>
            <div style={styles.formContainer}>
                <div style={styles.headerImage}>
                    <img style={{ height: '100%', width: '100%' }} src={require('../components/image/FH_logos.png')} alt="Logo" />
                </div>
                <span style={{ color: 'black', width: '30%', marginTop: '-6%', height: '8%' }}><h1>Welcome to</h1></span>
                <div style={styles.header2Image}>
                    <img style={{ height: '100%', width: '100%' }} src={require('../components/image/Film_hook.png')} alt="Film Hook" />
                </div>
                <div style={styles.changeinputContainer}>
                    <input
                        placeholder="What is your name?"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        style={styles.input}
                    />
                </div>
               
                    <div style={styles.changedate}>
                        <div>
                            <button onClick={() => setShowDatePicker(true)}>D.O.B</button>
                        </div>
                       
                    </div>
                    {showDatePicker && (
                        <input
                            type="date"
                            onChange={onDateChange}
                        />
                    )}
                    {dob && (
                        <div>{dob.toDateString()}</div>
                    )}
               
                <div>
                    <select
                        value={selectedGender}
                        onChange={(e) => setSelectedGender(e.target.value)}
                        style={{ height: 40, width: 200 }}
                    >
                        <option value="">Select Gender</option>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                        <option value="Transgender">Transgender</option>
                        <option value="others">Others</option>
                    </select>
                </div>
                <div>
                    <select
                        value={selectedCountry}
                        onChange={(e) => setSelectedCountry(e.target.value)}
                        style={{ height: 40, width: 200 }}
                    >
                        <option value="">Select Country</option>
                        {countries.map((country, index) => (
                            <option key={index} value={country.name}>
                                {country.name}
                            </option>
                        ))}
                    </select>
                </div>
                <div>
                    <select
                        value={selectedState}
                        onChange={(e) => setSelectedState(e.target.value)}
                        style={{ height: 40, width: 200 }}
                    >
                        <option value="">Select State</option>
                        {selectedCountry &&
                            countries
                                .find((country) => country.name === selectedCountry)
                                .states.map((state, index) => (
                                    <option key={index} value={state.name}>
                                        {state.name}
                                    </option>
                                ))}
                    </select>
                </div>
                <div>
                    <select
                        value={selectedDistrict}
                        onChange={(e) => setSelectedDistrict(e.target.value)}
                        style={{ height: 40, width: 200 }}
                    >
                        <option value="">Select District</option>
                        {selectedState &&
                            countries
                                .find((country) => country.name === selectedCountry)
                                .states.find((state) => state.name === selectedState)
                                .districts.map((district, index) => (
                                    <option key={index} value={district}>
                                        {district}
                                    </option>
                                ))}
                    </select>
                </div>
                <div>
                    <button onClick={handlepressNav}>STEP 2</button>
                </div>
            </div>
        </div>
    );
};

export default SignUp;